name: terraform apply for vmaas

on:
  push:
    branches:
      - main
    paths:
      - terraform/service/*.tf
      - terraform/instance/*.tf
      - instances/*/instance.yml
      - instances/*/bindings/*/binding.yml

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/checkout@v3
      - working-directory: terraform/service
        env:
          ARM_SUBSCRIPTION_ID: e1c85eff-0a2c-4268-9b6c-7d2ff9ca9848
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          cd terraform/service
          terraform init
          terraform apply -auto-approve
      - run: |
          git config --global user.email "bot@likvid.meshstack.io"
          git config --global user.name "Cloud Foundation bot"
          git add .
          git diff-index --quiet HEAD -- || git commit -m "terraform apply for vmaas"
          git pull --rebase
          git push
